cluster: "submit.py"
cluster-status: "status.py"
jobscript: "jobscript.sh"
jobs: 10
restart-times: 0
immediate-submit: false
verbose: false
max-jobs-per-second: 1
max-status-checks-per-second: 10
local-cores: 1
latency-wait: 60
rerun-incomplete: true  # recomended for cluster submissions
keep-going: false
default-resources: "mem_mb=5980"
use-singularity: true
use-conda: true
resources: gpu=2
cores: 16
cache: false
reason: true
singularity-args: "--bind /home/cs-pavl1/rds/evgeny,/usr/local/software/cuda/11.2,/usr/local/Cluster-Apps/cudnn/8.1_cuda-11.2/lib64:/cudnn,/tmp --nv --containall"
config:
  - deps=false
  - root=/home/cs-pavl1/rds/evgeny
  - cuda=/usr/local/software/cuda/11.2
  - cudnn=/cudnn
  - workspace=8000
  - numgpus=8
  # if compiling on CPU you might need to do mariancmake=-DBUILD_ARCH=core-avx2
  - mariancmake=""
  - gpus=""


# running on csd3 requires:
#  module load singularity
#  module load cudnn/8.1_cuda-11.2