verbose: true
use-singularity: true
use-conda: true
resources: gpu=1
cores: 8
cache: false
reason: true
singularity-args: "--bind $PWD/../data,$CUDA_INSTALL_ROOT,$CUDNN_INSTALL_ROOT,$PWD/../data/tmp:/tmp --nv --containall"
config:
  - deps=false
  - workspace=10000
  - numgpus=1
  - mariancmake=""
  - gpus=""
