name: bergamot-training
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - cmake=3.21.1
  - pip=21.2.2
  - pip:
    - sacrebleu==2.0.0
    - mtdata==0.3.2
    - fasttext==0.9.2
    - regex==2019.8.19
    - sacremoses==0.0.43
