datasets:
  original: <dataset0> # Original parallel corpus
  backtranslated: <dataset1> # Back-translated data

stages:
#  - pretrain
  - finetune


#pretrain:
#  - original 0.7
#  - backtranslated 0.3
#  - until original 2

# Fine-tuning only on original clean corpus until the early stopping
finetune:
  - original 1.0
  - until original inf


modifiers:
- UpperCase: 0.07 # Apply randomly to 10% of sentences
- TitleCase: 0.05
# TODO: enable typos, issue https://github.com/mozilla/firefox-translations-training/issues/262
#- Typos: 0.05

seed: 1111
num_fields: 2
