# https://discourse.translatelocally.com/t/marian-configuration-to-use/24
disp-freq: 1000
# use default learning rate 0.0002 for transformer-big https://github.com/marian-nmt/marian-dev/blob/master/src/common/aliases.cpp
# adjust learning rate if needed
# learn-rate: 0.0003 # Turn this down if you get a diverged model, maybe 0.0001
optimizer-delay: 2 # Roughly GPU devices * optimizer-delay = 8, but keep as an integer
lr-report: True
save-freq: 5000
valid-freq: 3000
valid-max-length: 300
valid-mini-batch: 8
early-stopping: 20
