# https://github.com/marian-nmt/marian-examples/tree/master/transformer
# https://github.com/marian-nmt/marian-examples/tree/master/wmt2017-uedin
dec-depth: 6
dim-vocabs: [32000, 32000]
enc-depth: 6
tied-embeddings-all: true
transformer-dropout: 0.1
type: transformer
